FROM jenkins/jenkins:lts

USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

# Install Blue Ocean plugin 

RUN jenkins-plugin-cli --plugins \
    blueocean \
    docker-workflow \
    git\
    workflow-aggregator

USER jenkins